global:
  evaluation_interval: 30s
  scrape_interval: 15s
scrape_configs:
  - job_name: locust-exporter
    static_configs:
      - targets:
          - locust-exporter:9646
  - job_name: pushgateway
    static_configs:
      - targets:
        - pushgateway:9091
rule_files:
  - /etc/prometheus/prometheus_rules.rules